hand_config:
  joints:
    - name: thumb_proximal_yaw_joint
      finger: thumb
      role: yaw
      limit_max: 1.308
      default_position: 0.0
    - name: thumb_proximal_pitch_joint
      finger: thumb
      role: pitch
      limit_max: 0.6
      default_position: 0.0
    - name: index_proximal_joint
      finger: index
      role: flex
      limit_max: 1.47
      default_position: 0.0
    - name: middle_proximal_joint
      finger: middle
      role: flex
      limit_max: 1.47
      default_position: 0.0
    - name: ring_proximal_joint
      finger: ring
      role: flex
      limit_max: 1.47
      default_position: 0.0
    - name: pinky_proximal_joint
      finger: pinky
      role: flex
      limit_max: 1.47
      default_position: 0.0

  publish_rate: 10  # Hz
